### ISSUE TITLE
Low Priority: Typo in readme

### ISSUE THREAD

**Issue by nightduck** [ynsta/steamcontroller#59] opened 2017-03-09 18:46 UTC
Under usage, where is says "Stop: sc-xbox.py stop or sc-xbox.py stop" (it says xbox twice)
It should say Stop: sc-xbox.py stop or sc-desktop.py stop"

**Comment by Co2p** [comment] 2017-03-30 09:47
Duplicate of #53

**Closed** 2017-07-06 08:21 UTC
